# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Mount bazel action cache
        uses: actions/cache@v3
        if: always()
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Mount bazel repo cache
        uses: actions/cache@v3
        if: always()
        with:
          path: "~/.cache/bazel-repo"
          key: bazel-repo

      - name: build jacocorunner
        env:
          # Bazelisk will download bazel to here
          XDG_CACHE_HOME: ~/.cache/bazel-repo
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: >-
          bazel
          --bazelrc=.github/workflows/ci.bazelrc
          --bazelrc=.bazelrc
          build
          //java/com/google/testing/coverage
          &&
          cp bazel-bin/java/com/google/testing/coverage/JacocoCoverage_jarjar_deploy.jar ./jacococoverage.${{ env.RELEASE_VERSION }}.jar
      - name: Release
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./jacococoverage.${{ env.RELEASE_VERSION }}.jar
